#!/bin/bash

while getopts ":1 :2 :d :m:h" opt; do
  case $opt in
    h)
	echo "						Auto-git v1.1"
	echo "		Tired of typing in the same three lines of code in oreder to make changes to your Github?"
	echo "	Autogit is here to the rescue! Input a message with the (-m) flag or simple use one of the two auto"
	echo "	comments. Still a lot of room for options to be updated. Stay tuned on my github: "
	echo "	<https://github.com/Brian-S-Park/Ubuntu-Start-Message> Thanks for checking it out!"
	echo ""
	echo "						[Help menu]" 
	echo "	-h	help"
	echo "	-m	Input custom message to commit"
	echo "	-1	Automatic message 'Minor Changes to Github'"
	echo "	-2	Automatic message 'Major Changes to Github'"
	echo "	-d	Automatic message 'Updated Version [current date]'"
	echo "	-r	Create new repository and initializes it"
	echo ""
      exit 1
      ;;
    m)
	git add .
        git commit -m "$OPTARG"
        git push origin main
	echo "Github was Updated!"
      ;;
    1)
	git add .
        git commit -m "Minor Changes to project"
        git push origin main
	echo "Minor change to Github"
      ;;
    2)
	git add .
        git commit -m "Major Changes to project"
        git push origin main
        echo "Major change to Github"
      ;;
    d)
	git add .
	DATE=$(date +%m/%d/%Y)
        git commit -m "Updated Version - $DATE"
	git push origin main
        echo "Github Updated!"
      ;;
     r)
        gh repo create $OPTARG
        cd $OPTARG
        git init
        touch README.md
        git add README.md
        git commit -m "first commit"
        git branch -M main
        git push -u origin main
        echo "Repository was Created!"
      ;;
    \?)
      echo "Invalid option: -$OPTARG" >&2
      exit 1
      ;;
    :)
      echo "Option -$OPTARG requires an argument." >&2
      exit 1
      ;;
  esac
done


